version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python run.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image : postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mhst
    ports:
      - '5433:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql


